### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [eifinger/PyFoldingAtHomeControl#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.5.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pyfoldingathomecontrol -w /tmp/ext pyfoldingathomecontrol==1.5.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pyfoldingathomecontrol==1.5.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/955/aa5aeacc0d93a/PyFoldingAtHomeControl-1.5.0.tar.gz (6.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-abf0tya8/pyfoldingathomecontrol/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-abf0tya8/pyfoldingathomecontrol/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-abf0tya8/pyfoldingathomecontrol/pip-egg-info
         cwd: /tmp/pip-wheel-abf0tya8/pyfoldingathomecontrol/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-abf0tya8/pyfoldingathomecontrol/setup.py", line 20, in <module>
        install_requires=list(val.strip() for val in open('requirements.txt')),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by eifinger** [comment]
I released v1.5.1 this fixes it for me:
```bash
pip3 install wheel
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.34.2
(venvtest) eifinger@DESKTOP:~/PyFoldingAtHomeControl$ pip3 wheel --no-binary pyfoldingathomecontrol -w /tmp/ext pyfoldingathomecontrol==1.5.1
Collecting pyfoldingathomecontrol==1.5.1
  Using cached https://files.pythonhosted.org/packages/2f/92/57625def222e241df17ec2c1a362226d041319dd7a2179b94df4b544b635/PyFoldingAtHomeControl-1.5.1.tar.gz
Building wheels for collected packages: pyfoldingathomecontrol
  Running setup.py bdist_wheel for pyfoldingathomecontrol ... done
  Stored in directory: /tmp/ext
Successfully built pyfoldingathomecontrol
```

**Comment by eifinger** [comment]
I figured this was an automated issue so I will close it. Thank you @thatch

**Comment by thatch** [comment]
Confirmed, thanks!  (It's only half-automated.)
